.att_syntax
"?ComputeCarMassAndInertia_454410@@YG?AVFix16@@V1@000PAV1@@Z":
.global "?ComputeCarMassAndInertia_454410@@YG?AVFix16@@V1@000PAV1@@Z"
sub $0x24,%esp
mov 0x30(%esp),%eax
push %ebx
cltd
push %ebp
push %esi
mov %eax,%esi
mov "?kQuarter_677D78@@3VFix16@@A",%eax
push %edi
mov %edx,%edi
cltd
mov %eax,%ebx
mov 0x3C(%esp),%eax
mov %edx,%ebp
push %edi
cltd
push %esi
push %edi
push %esi
mov %eax,0x3C(%esp)
mov %edx,0x40(%esp)
call "__allmul"
mov $0xE,%ecx
call "__allshr"
cltd
push %ebp
push %ebx
push %edx
push %eax
call "__allmul"
mov $0xE,%ecx
call "__allshr"
mov 0x30(%esp),%ecx
mov %eax,0x3C(%esp)
mov 0x2C(%esp),%eax
push %ecx
push %eax
push %ecx
push %eax
call "__allmul"
mov $0xE,%ecx
call "__allshr"
mov 0x3C(%esp),%ecx
push %edi
add %eax,%ecx
mov $0x2AAAAAAB,%eax
imul %ecx
sar $1,%edx
mov %edx,%eax
push %esi
shr $0x1F,%eax
add %eax,%edx
push %ebp
push %ebx
mov %edx,0x4C(%esp)
call "__allmul"
mov $0xE,%ecx
call "__allshr"
mov %eax,0x10(%esp)
mov 0x44(%esp),%eax
cltd
mov %eax,%esi
mov 0x48(%esp),%eax
mov %edx,%edi
cltd
push %edi
push %esi
push %edx
push %eax
call "__allmul"
mov $0xE,%ecx
call "__allshr"
mov %eax,%ecx
mov 0x3C(%esp),%eax
cltd
mov %eax,0x2C(%esp)
mov %ecx,%eax
mov %edx,0x30(%esp)
mov %ecx,0x44(%esp)
cltd
mov %eax,0x24(%esp)
mov %edx,0x28(%esp)
mov 0x30(%esp),%ecx
push %ecx
mov 0x30(%esp),%ecx
push %ecx
push %edx
push %eax
call "__allmul"
mov $0xE,%ecx
call "__allshr"
mov %eax,0x14(%esp)
mov 0x40(%esp),%eax
neg %eax
cltd
push %ebp
push %ebx
push %edx
push %eax
call "__allmul"
mov $0xE,%ecx
call "__allshr"
mov 0x48(%esp),%edx
mov %eax,0x40(%esp)
mov "?kOne_677F54@@3VFix16@@A",%eax
push %edi
sub %edx,%eax
push %esi
cltd
push %edx
push %eax
call "__allmul"
mov $0xE,%ecx
call "__allshr"
mov %eax,0x18(%esp)
cltd
mov %edx,%ebp
mov 0x30(%esp),%edx
mov %eax,%ebx
mov 0x2C(%esp),%eax
push %edx
push %eax
push %ebp
push %ebx
call "__allmul"
mov $0xE,%ecx
call "__allshr"
mov %eax,0x1C(%esp)
mov 0x40(%esp),%eax
cltd
push %ebp
push %ebx
push %edx
push %eax
call "__allmul"
mov $0xE,%ecx
call "__allshr"
mov 0x10(%esp),%ebx
mov 0x28(%esp),%ecx
mov %eax,%ebp
mov %ebx,%eax
push %ecx
mov 0x28(%esp),%ecx
cltd
push %ecx
push %edx
push %eax
call "__allmul"
mov $0xE,%ecx
call "__allshr"
add %ebp,%eax
mov $0xE,%ecx
cltd
call "__allshl"
push %edi
push %esi
push %edx
push %eax
call "__alldiv"
mov 0x4C(%esp),%esi
mov %eax,(%esi)
sub %ebx,%eax
mov %eax,0x48(%esp)
mov %eax,0x3C(%esp)
lea 0x48(%esp),%edx
lea 0x20(%esp),%eax
push %edx
lea 0x40(%esp),%ecx
push %eax
lea 0x2C(%esp),%edx
push %ecx
push %edx
lea 0x54(%esp),%ecx
call "?Multiply_408680@Fix16@@QBE?AV1@ABV1@@Z"
mov %eax,%ecx
call "?Multiply_408680@Fix16@@QBE?AV1@ABV1@@Z"
push %eax
lea 0x30(%esp),%eax
push %eax
lea 0x1C(%esp),%ecx
call "??HFix16@@QBE?AV0@ABV0@@Z"
mov (%eax),%ecx
lea 0x40(%esp),%edx
lea 0x48(%esp),%eax
mov %ecx,0x10(%esp)
push %edx
push %eax
mov %esi,%ecx
call "?Subtract_436A00@Fix16@@QBE?AV1@ABV1@@Z"
lea 0x3C(%esp),%ecx
push %eax
lea 0x44(%esp),%edx
push %ecx
lea 0x34(%esp),%eax
push %edx
push %eax
mov %esi,%ecx
call "?Subtract_436A00@Fix16@@QBE?AV1@ABV1@@Z"
lea 0x2C(%esp),%ecx
push %eax
push %ecx
lea 0x28(%esp),%ecx
call "?Multiply_408680@Fix16@@QBE?AV1@ABV1@@Z"
mov %eax,%ecx
call "?Multiply_408680@Fix16@@QBE?AV1@ABV1@@Z"
lea 0x20(%esp),%edx
push %eax
push %edx
lea 0x24(%esp),%ecx
call "??HFix16@@QBE?AV0@ABV0@@Z"
mov (%eax),%eax
lea 0x4C(%esp),%ecx
mov 0x38(%esp),%esi
push %ecx
push %esi
lea 0x18(%esp),%ecx
mov %eax,0x54(%esp)
call "??HFix16@@QBE?AV0@ABV0@@Z"
mov %esi,%eax
pop %edi
pop %esi
pop %ebp
pop %ebx
add $0x24,%esp
ret $0x18

