mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Ambulance_110.cpp.obj Ambulance_110.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Bink.cpp.obj Bink.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o BurgerKing_67F8B0.cpp.obj BurgerKing_67F8B0.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Camera.cpp.obj Camera.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o CarAI_78.cpp.obj CarAI_78.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o CarInfo_808.cpp.obj CarInfo_808.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o CarPhysics_B0.cpp.obj CarPhysics_B0.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Car_BC.cpp.obj Car_BC.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o char.cpp.obj char.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Char_Pool.cpp.obj Char_Pool.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Cranes.cpp.obj Cranes.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o crt_stubs.cpp.obj crt_stubs.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o dma_video.cpp.obj dma_video.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Door_4D4.cpp.obj Door_4D4.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Draw.cpp.obj Draw.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o eager_benz.cpp.obj eager_benz.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o error.cpp.obj error.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Firefighters.cpp.obj Firefighters.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o fix16.cpp.obj fix16.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Fix16_Point.cpp.obj Fix16_Point.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Frontend.cpp.obj Frontend.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o frosty_pasteur_0xC1EA8.cpp.obj frosty_pasteur_0xC1EA8.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Gang.cpp.obj Gang.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Garage_48.cpp.obj Garage_48.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Generators.cpp.obj Generators.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o gtx_0x106C.cpp.obj gtx_0x106C.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Hud.cpp.obj Hud.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o jolly_poitras_0x2BC0.cpp.obj jolly_poitras_0x2BC0.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o keybrd_0x204.cpp.obj keybrd_0x204.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Kfc_1E0.cpp.obj Kfc_1E0.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o MapRenderer.cpp.obj MapRenderer.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o map_0x370.cpp.obj map_0x370.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Mike_A80.cpp.obj Mike_A80.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o miss2_0x11C.cpp.obj miss2_0x11C.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Montana.cpp.obj Montana.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o NetPlay.cpp.obj NetPlay.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Network_20324.cpp.obj Network_20324.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Object_3C.cpp.obj Object_3C.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Object_5C.cpp.obj Object_5C.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Orca_2FD4.cpp.obj Orca_2FD4.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Particle_4C.cpp.obj Particle_4C.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Particle_8.cpp.obj Particle_8.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Ped.cpp.obj Ped.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o PedGroup.cpp.obj PedGroup.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Player.cpp.obj Player.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Police_38.cpp.obj Police_38.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Police_7B8.cpp.obj Police_7B8.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o PublicTransport.cpp.obj PublicTransport.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o RouteFinder.cpp.obj RouteFinder.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o sad_mirzakhani.cpp.obj sad_mirzakhani.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o sharp_pare_0x15D8.cpp.obj sharp_pare_0x15D8.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o sound_obj.cpp.obj sound_obj.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o sprite.cpp.obj sprite.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Taxi_4.cpp.obj Taxi_4.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o text_0x14.cpp.obj text_0x14.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o thirsty_lamarr.cpp.obj thirsty_lamarr.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o TrafficLights_194.cpp.obj TrafficLights_194.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Weapon_30.cpp.obj Weapon_30.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o winmain.cpp.obj winmain.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o Wolfy_3D4.cpp.obj Wolfy_3D4.cpp.asm
mingw64\bin\as --32 -mmnemonic=intel -msyntax=intel -mnaked-reg -o youthful_einstein.cpp.obj youthful_einstein.cpp.asm
